---
abstract: 'A Template Toolkit renderer for WebNano with dynamic search paths'
author:
  - 'Zbigniew Lukasiak <zby@cpan.org>'
build_requires:
  Test::More: 0
  WebNano::Controller: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.102400'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebNano-Renderer-TT
requires:
  File::Spec: 0
  Object::Tiny::RW: 0
  Template: 0
resources:
  repository: http://github.com/zby/WebNano-Renderer-TT
version: 0.002
